type Data = {
  name: string;
  sex: boolean;
  price: number;
  image: string;
  type: string;
};

const data: Data[] = [
  {
    name: "S/PRO SUPRA BOA 130",
    sex: true,
    price: 650.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO SUPRA BOA 120",
    sex: true,
    price: 600.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO SUPRA BOA 105",
    sex: false,
    price: 550.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO SUPRA BOA 110",
    sex: true,
    price: 550.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO SUPRA BOA 95",
    sex: false,
    price: 500.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO ALPHA 120",
    sex: true,
    price: 500.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO ALPHA 130 EXPERT LINE",
    sex: true,
    price: 650.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO ALPHA 100",
    sex: false,
    price: 450.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "S/PRO ALPHA 90",
    sex: false,
    price: 400.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "SHIFT PRO 130 AT",
    sex: true,
    price: 700.0,
    image: "../assets/shoes-background.svg",
    type: "Shoes",
  },
  {
    name: "ADDIKT PRO",
    sex: true,
    price: 800.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "ADDIKT",
    sex: true,
    price: 750.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "E S/MAX 8 XT",
    sex: true,
    price: 630.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "S/MAX 12",
    sex: true,
    price: 900.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "S/MAX 10",
    sex: true,
    price: 750.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "S/MAX 8",
    sex: true,
    price: 600.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "S/MAX 10 XT",
    sex: true,
    price: 780.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "QST ECHO 106",
    sex: true,
    price: 780.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "QST BLANK",
    sex: true,
    price: 830.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "QST 106",
    sex: true,
    price: 730.0,
    image: "../assets/shoes-background.svg",
    type: "Skis",
  },
  {
    name: "MTN CARBON S3",
    sex: true,
    price: 170.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "MTN CARBON S3 LTD",
    sex: true,
    price: 160.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "MTN OUTDOOR",
    sex: true,
    price: 170.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "MTN ALU S3",
    sex: true,
    price: 120.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "QUEST CARBON FOLDABLE",
    sex: true,
    price: 160.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "QUEST ALU VARIO",
    sex: true,
    price: 90.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "MTN",
    sex: true,
    price: 55.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "S/RACE CARBON",
    sex: true,
    price: 120.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "S/RACE GS",
    sex: true,
    price: 85.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "S/RACE ALU",
    sex: true,
    price: 95.0,
    image: "../assets/shoes-background.svg",
    type: "Sticks",
  },
  {
    name: "RADIUM PRIME SIGMA PHOTOCHROMIC",
    sex: true,
    price: 280.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "RADIUM PRIME SIGMA",
    sex: true,
    price: 260.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "RADIUM PRO SIGMA PHOTOCHROMIC",
    sex: true,
    price: 200.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "RADIUM PRO SIGMA",
    sex: true,
    price: 180.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "RADIUM PRO",
    sex: true,
    price: 160.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "RADIUM PHOTOCHROMIC",
    sex: true,
    price: 130.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "RADIUM SIGMA",
    sex: true,
    price: 130.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "RADIUM",
    sex: true,
    price: 110.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "SENTRY PRIME SIGMA PHOTOCHROMIC",
    sex: true,
    price: 230.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "SENTRY PRIME SIGMA",
    sex: true,
    price: 210.0,
    image: "../assets/shoes-background.svg",
    type: "Mask",
  },
  {
    name: "PIONEER LT",
    sex: true,
    price: 110.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "ICON LT PRO",
    sex: false,
    price: 150.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "ICON LT",
    sex: false,
    price: 110.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "DRIVER PRIME SIGMA PHOTO MIPS PLUS",
    sex: true,
    price: 430.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "DRIVER PRIME SIGMA PLUS",
    sex: false,
    price: 330.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "S/RACE",
    sex: true,
    price: 250.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "BRIGADE INDEX",
    sex: false,
    price: 130.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "HUSK PRIME MIPS",
    sex: true,
    price: 250.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "MTN LAB",
    sex: true,
    price: 180.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
  {
    name: "ICON LT VISOR FLS",
    sex: false,
    price: 650.0,
    image: "../assets/shoes-background.svg",
    type: "Headset",
  },
];

export default data;
